### PR TITLE
update waf url to use https

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by wm4** [comment]
Why doesn't it use bootstrap.py? What's the reason you want https?

**Comment by vszakats** [comment]
Sorry, no idea about why it's designed the way it is, anyhow the end result is that it pulls a component from an unencrypted http link (revealed by `brew upgrade` output run just now), while the same resource can be accessed using a secure https link. This patch switches to the latter.

**Comment by wm4** [comment]
> it pulls a component via an unencrypted http link 

Yes, but it explicitly verifies the file's checksum.

Anyway, I don't mind; I don't even maintain the homebrew scripts and I was just curious.

**Comment by vszakats** [comment]
Secure connection offers more over content integrity, so if it's available it's good practice to use it in most cases.

**Comment by vszakats** [comment]
Looks like this is unaccepted. I've left a similar note in the Homebrew [PR](https://github.com/Homebrew/homebrew/pull/36952). Closing this one.

**Comment by pigoz** [comment]
We didn't use https previously because the waf.io domain uses a self signed certificate. This has been discussed on the main mpv repository for `./bootstrap.py`, I don't know if the situation improved since then (if it did, we should also update `./bootstrap.py`)

**Comment by vszakats** [comment]
Thanks for the feedback. The site has a CACert.org certificate, which is better than a self-signed one, but indeed not accepted by all client. I'll remove my Homebrew PR comment. [ In my particular test the client (curl + CAfile) didn't complain. ]

**Pull request closed without merging**
